version: 0.2

env:
  variables:
    PYTHONPATH: "src/main/python/demo_py"

phases:
  install:
    commands:
      - echo install phase `date`
      - pip install --upgrade pip
      - pip install boto3 --upgrade
      - pip install pyyaml --upgrade
      - pip install yamllint --upgrade
  pre_build:
    commands:
      - echo pre_build phase `date`
  build:
    commands:
      - echo build phase `date`
      - echo build phase `pwd`
      - python src/main/python/demo_py/demo_driver.py src/main/python/demo_py/config.test
      - python src/main/python/demo_py/test_target.py

  post_build:
    commands:
      - echo post_build phase `date`

artifacts:
  base-directory: src/main/python/demo_py
  files:
    - demo_driver.py
    - target.py
